[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/ripoai"
  to = "/.netlify/functions/ripoai"
  status = 200

[[redirects]]
  from = "/api/link-preview"
  to = "/.netlify/functions/link-preview"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
